environment:
  matrix:
  - TOXENV: "py27"
  - TOXENV: "py35"
  - TOXENV: "py36"

install:
  - C:\Python36\python -m pip install tox wheel
  - C:\Python27\python -m pip install wheel

build_script:
  - C:\Python36\python setup.py bdist_wheel
  - C:\Python27\python setup.py bdist_wheel

test_script:
  - C:\Python36\scripts\tox

deploy_script:
  # Only perform on tags
  #- if %APPVEYOR_REPO_TAG% equ false exit
  # Import function to wait for other Appveyor jobs and Travis Jobs
  - . ./appveyor_wait_for_other_jobs_complete.ps1
  - . ./appveyor_wait_for_travis.ps1
  # Tell first appveyor job to wait for other Appveyor jobs + Travis jobs
  # From https://gist.github.com/IlyaFinkelshteyn/dc0b08593cb0babff2bd84dd05c4ee42
  # From https://gist.github.com/IlyaFinkelshteyn/14750254656005c25c359371d7b4359f
  - SET TRAVIS_API_TOKEN='FOO'
  - allJobsFinished
  - allCIsFinished
  # All jobs successfull, proceed to deploy
  - SET PYPI_USERNAME=SVG_LIB_USERNAME
  - SET PYPI_PASSWORD=SVG_LIB_PASSWORD
  - SET PYPI_REPO_URL=https://test.pypi.org/legacy/
  - C:\Python36\python -m pip install twine
  - twine upload --repository-url %PYPI_REPO_URL% dist/* -u %PYPI_USERNAME% - p %PYPI_PASSWORD%

artifacts:
  - path: ./dist/*.whl
