environment:
  matrix:
  - TOXENV: "py27"
  - TOXENV: "py35"
  - TOXENV: "py36"

install:
  - C:\Python36\python -m pip install tox wheel
  - C:\Python27\python -m pip install wheel

build_script:
  - C:\Python36\python setup.py bdist_wheel
  - C:\Python27\python setup.py bdist_wheel

test_script:
  - C:\Python36\scripts\tox

artifacts:
  - path: ./dist/*.whl
