environment:
  matrix:
  - TOXENV: "py27"
  - TOXENV: "py35"
  - TOXENV: "py36"

install:
  - C:\Python36\python -m pip install tox

build_script:
  - C:\Python36\python setup.py bdist_wheel
  - C:\Python27\python setup.py bdist_wheel

test_script:
  - C:\Python36\scripts\tox

deploy_script:
  #- if %APPVEYOR_REPO_TAG% equ false exit
  - SET PYPI_USERNAME=SVG_LIB_USERNAME
  - SET PYPI_PASSWORD=SVG_LIB_PASSWORD
  - SET PYPI_REPO_URL=https://test.pypi.org/legacy/
  - C:\Python36\python -m pip install twine
  - twine upload --repository-url %PYPI_REPO_URL% dist/* -u %PYPI_USERNAME% - p %PYPI_PASSWORD%

artifacts:
  - path: ./dist/*.whl
